services:
   web: 
    image: infracloudio/csvserver:latest
    ports:
    - 9393:9300
    volumes:
    - /home/rahul/inputFile:/csvserver/inputdata
    environment:
    - CSVSERVER_BORDER=Orange
   web2:
    image: prom/prometheus:v2.22.0
    ports:
    - 9090:9090
    volumes:
    - /home/rahul/csvserver/solution/prometheus.yaml:/etc/prometheus/prometheus.yml
    

