scrape_configs:
          - job_name:       'prom1'

                # Override the global default and scrape targets from this job every 5 seconds.
            scrape_interval: 5s
                #
            static_configs:
              - targets: ['172.28.1.237:9393']
                labels:
                  group: 'prometheus'
